namespace PEXC.Case.Domain;

public class CaseHistoricFieldsEntity
{
    public string? CaseEndTemplateLeveragingDdScale { get; set; }
    public string? TitleOfMarketOverviewsPostedOnGXC { get; set; }
    public string? IndustrySectorsAnalyzedAsPartOfDd { get; set; }
    public string? AdvancedAnalyticsUsageHistorical { get; set; }
    public IReadOnlyList<string>? AdvancedAnalyticsUsageDetails { get; set; }
    public string? IndustryTrendsAndIssues { get; set; }
    public string? SectorInsights { get; set; }
    public string? CaseCrackingActivities { get; set; }
    public bool? IndustryReview { get; set; }
    public bool? CompetitorReview { get; set; }
    public bool? CustomerAnalysis { get; set; }
    public bool? CompetitorAnalysis { get; set; }
    public bool? NewBusinessGrowthAdjacency { get; set; }
    public bool? NewBusinessGrowthInternational { get; set; }
    public bool? ExistingBusinessGrowthSustainable { get; set; }
    public bool? ExistingBusinessGrowthCustomer { get; set; }
    public bool? ExistingBusinessGrowthMarketing { get; set; }
    public bool? ExistingBusinessGrowthSalesForce { get; set; }
    public bool? ExistingBusinessGrowthPricing { get; set; }
    public bool? ExistingBusinessGrowthChannelManagement { get; set; }
    public bool? CostProcurement { get; set; }
    public bool? CostSupplyChainDistribution { get; set; }
    public bool? CostGandA { get; set; }
    public bool? CostManufacturing { get; set; }
    public bool? CostProductComplexity { get; set; }
    public bool? CostItOptimization { get; set; }
    public bool? CostSustainedCostTransformation { get; set; }
    public bool? CostCapabilitySourcing { get; set; }
    public bool? CashNwcOptimization { get; set; }
    public bool? CashCapexOptimization { get; set; }
    public bool? CompanyOperationsReview { get; set; }
    public bool? MgmtPlanReview { get; set; }
    public string? Other { get; set; }
    public bool? ROSRMS { get; set; }
    public bool? RCP { get; set; }
    public bool? CustomerSurvey { get; set; }
    public bool? CHAID { get; set; }
    public bool? DerivedDemand { get; set; }
    public bool? BusinessDefinition { get; set; }
    public string? AnyOtherAnalysis { get; set; }
    public bool? SurveyInstruments { get; set; }
    public string? ProposalCollected { get; set; }
    public bool? CostRnD { get; set; }
    public bool? CostServiceOptimization { get; set; }
    public string? DigitalComponent { get; set; }
    public string? DigitalFocusComments { get; set; }
    public bool? NPS { get; set; }
    public string? OpsDdComponent { get; set; }
    public bool? OrganizationDesignOverallFunctional { get; set; }
    public string? CaseTypeCluster { get; set; }

    public string? ApacDidTheDealProceedWithClient { get; set; }
    public string? ApacDidTheDealProceedWithOthers { get; set; }
    public string? ApacIncludeInPEDdCount { get; set; }
    public string? ApacIncludeInTotalCaseCountExcludingCdd { get; set; }
    public string? ApacIncludeInTotalCaseCountIncludingCdd { get; set; }
    public string? OperationalComponent { get; set; }
    public bool? SearchReady { get; set; }
    public string? CaseExamples { get; set; }
    public string? Consortium { get; set; }
    public string? ConsortiumDetails { get; set; }
    public string? EmeaBackground { get; set; }
    public string? EmeaCallLeader { get; set; }
    public DateTime? EmeaDateOfCall { get; set; }
    public string? EmeaExpertNetworkDetails { get; set; }
    public string? EmeaExpertNetworkFeedback { get; set; }
    public string? EmeaExpertNetworkNps { get; set; }
    public string? EmeaExpertNetworkUsed { get; set; }
    public string? EmeaExternalToolProviderandScope { get; set; }
    public string? EmeaExternalToolsUtilised { get; set; }
    public string? EmeaInternalExperts { get; set; }
    public string? EmeaKeyDdQuestions { get; set; }
    public string? EmeaKeySources { get; set; }
    public string? EmeaSellingPartners { get; set; }
    public string? EmeaServingPartners { get; set; }
    public string? EmeaSurveyProviderDetails { get; set; }
    public string? EmeaSurveyProviderFeedback { get; set; }
    public string? EmeaSurveyProviderNps { get; set; }
    public string? EmeaSurveyProviderUsed { get; set; }
    public string? IsKMTeam { get; set; }
    public string? KeySectorCodified { get; set; }
    public string? LegalScrubbedVersion { get; set; }
    public string? MatchingBainDealDatabaseName1 { get; set; }
    public string? MatchingBainDealDatabaseName2 { get; set; }
    public string? MultibidderSituation { get; set; }
    public string? SanitisedClientName { get; set; }
    public string? SourceFolder { get; set; }
    public string? CreateFolder { get; set; }
    public string? RemoveCMPermission { get; set; }
    public DateTime? ApacReminder1 { get; set; }
    public DateTime? ApacReminder2 { get; set; }
    public DateTime? ApacReminder3 { get; set; }
    public string? FN_BP { get; set; }
    public string? FN_CM { get; set; }
    public string? FN_KM { get; set; }
    public string? TargetPrivatePublic { get; set; }
    public DateTime? MigrationDate { get; set; }
    // Old id of the case migrated from PEXC 1.0
    public string? MigrationId { get; set; }
    // Old UniqueId of the case migrated from PEXC 1.0
    public string? MigrationUniqueId { get; set; }
}